name: no-build build
on: [push, pull_request]

jobs:
  macos:
    strategy:
      matrix:
        lang: [c, c++]
    runs-on: macos-latest
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Run tests
        run: |
          clang -x ${{ matrix.lang }} -o nob nob.c -DPLATFORM_GITHUB_WORKFLOW
          ./nob 
          build/main

      - uses: actions/upload-artifact@v7
        with:
          name: 'test-artifact'
          path: 'build/main'
        
  ubuntu:
    strategy:
      matrix:
        cc: [gcc, clang]
        lang: [c, c++]
    runs-on: ubuntu-latest
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Run tests
        run: |
          ${{ matrix.cc }} -x ${{ matrix.lang }} -o nob nob.c -DPLATFORM_GITHUB_WORKFLOW
          ./nob
          build/main

      - uses: actions/upload-artifact@v7
        with:
          name: 'test-artifact'
          path: 'build/main'
  windows:
    strategy:
      matrix:
        mode: ["/TC", "/std:c++20 /TP"]
    runs-on: windows-latest
    steps:
      - name: Clone GIT repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: vswhere
        run: vswhere
      - name: Build tests
        
        shell: cmd
        # cl.exe isn't available as-is in Github images because they don't want
        # to, so we need to pull env vars ourselves. Refs:
        # https://github.com/actions/runner-images/issues/6205#issuecomment-1241573412
        # https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#create-your-own-command-prompt-shortcut
        run: |
          call "C:\\Program Files\\Microsoft Visual Studio\\18\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          cl.exe ${{ matrix.mode }} /Fe:nob nob.c -DPLATFORM_GITHUB_WORKFLOW
          nob.exe
          build\\main.exe

      - uses: actions/upload-artifact@v7
        with:
          name: 'test-artifact'
          path: 'build/main'
